// wb-tutor-tts — Edvana Whiteboard Tutor
//
// Speaks the tutor's reply aloud via ElevenLabs. Takes the reply TEXT
// (already generated by wb-tutor-turn) and returns synthesized audio.
// Audio is generated fresh per turn and never persisted — the browser plays
// it once and discards it, same as the student's recorded clip.
import { serve } from "https://deno.land/std@0.168.0/http/server.ts";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers":
    "authorization, x-client-info, apikey, content-type, x-supabase-client-platform",
};

const DEFAULT_VOICE_ID = "qctHfkHRO4VywbOJNhcg";
const MAX_CHARS = 2000; // a single tutor reply is 1-2 sentences; this is a generous cap

interface TtsRequest {
  text: string;
}

serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response(null, { headers: corsHeaders });
  }
  try {
    const apiKey = Deno.env.get("ELEVEN_API_KEY");
    if (!apiKey) {
      return json({ error: "TTS not configured (set ELEVEN_API_KEY)" }, 500);
    }

    const { text } = (await req.json()) as TtsRequest;
    if (!text || !text.trim()) {
      return json({ error: "text is required" }, 400);
    }
    const clipped = text.trim().slice(0, MAX_CHARS);

    const voiceId = Deno.env.get("ELEVEN_VOICE_ID") || DEFAULT_VOICE_ID;

    const res = await fetch(
      `https://api.elevenlabs.io/v1/text-to-speech/${voiceId}`,
      {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          "xi-api-key": apiKey,
          Accept: "audio/mpeg",
        },
        body: JSON.stringify({
          text: clipped,
          model_id: "eleven_turbo_v2_5",
          voice_settings: { stability: 0.5, similarity_boost: 0.75 },
        }),
      },
    );

    if (!res.ok) {
      const detail = await res.text();
      return json({ error: `ElevenLabs error ${res.status}: ${detail.slice(0, 300)}` }, 502);
    }

    const audio = await res.arrayBuffer();
    return new Response(audio, {
      status: 200,
      headers: { ...corsHeaders, "Content-Type": "audio/mpeg" },
    });
  } catch (err) {
    return json({ error: err instanceof Error ? err.message : "Unknown error" }, 500);
  }
});

function json(body: unknown, status: number): Response {
  return new Response(JSON.stringify(body), {
    status,
    headers: { ...corsHeaders, "Content-Type": "application/json" },
  });
}
